name: CI
run-name: Continuous Integration

on:
  pull_request:
    paths:
      - 'src'

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: rust:1.68
    steps:
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: cargo fmt
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.68
    steps:
      - uses: actions/checkout@v3
      - run: cargo build
