name: CI
run-name: Continuous Integration

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: rust:1.68
    steps:
      - cargo fmt
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.68
    steps:
      - cargo build
